### ISSUE TITLE
Should we be more prescriptive around sponsor/large enterprise behavior?

### ISSUE THREAD

**Issue by jdreed** [mirjak/draft-kuehlewind-shmoo-remote-fee#2]
Sponsor organizations receive a limited number of free registrations, based on their sponsor level.  A remote meeting does not incur all the travel costs normally borne by those organizations.  Should we encourage organizations to donate some of their free registrations to a fee waiver program, if they can afford it?  Alternatively, should we encourage them to apply those registrations to members of their communities that might not otherwise attend?

**Comment by jlivingood** [comment]
I recommend keeping this out of scope for the document, in particular because it will constrain the flexibility to adapt sponsorship offers/deals. And whenever we ask 'should we be more prescriptive' I think the answer is no. ;-)

**Comment by mirjak** [comment]
Agreed. @jdreed  can we close this issue?

**Comment by jdreed** [comment]
Closing.
