### ISSUE TITLE
Lars's comment on inconsistencies

### ISSUE THREAD

**Issue by richsalz** [mirjak/draft-kuehlewind-shmoo-remote-fee#25]
Elsewhere, Lars wrote:

"I'll note that there remain some internal inconsistencies in the document that need to be addressed, for example, the very next paragraph says "regardless of whether the meeting has a physical presence", which implies the principles intend to hybrid meetings, which as discussed on the list they can't (at least not at BCP-level strength.) And further down it says "if remote participation is provided, there should always be a free option", which has similar issues."

**Comment by richsalz** [comment]
I suggest we merge the existing PR's, publish a new draft, then tackle this.

**Comment by mirjak** [comment]
We should anyway wait till end of WGLC before we submit the new version, which will be mid of next week.

**Comment by mirjak** [comment]
@larseggert after the re-charter I think we can close this remaining issue and the respective PR?

**Comment by larseggert** [comment]
Yes, but that is still pending.

I would still encourage a pass over the document to make sure it is then clear everywhere that it **does** apply to hybrid meetings.

**Comment by mirjak** [comment]
I made another review and there are 2-3 occasions where we mention the free option and they are all clear that it applies to all remote participation, with or with in-person component. Closing now.
