### ISSUE TITLE
Value of open participation

### ISSUE THREAD

**Issue by mirjak** [mirjak/draft-kuehlewind-shmoo-remote-fee#4]
I guess if we want we could be even more clear/make stronger statements of the value of this principle in a) keeping the process open which is seen widely as a big benefit of the IETF compared to other SDOs and b) attracting new participants which is essential for the sustainability of the IETF and c) preserving expertise and knowledge indepentent of someone's employment constraints.

**Comment by jlivingood** [comment]
I'm not sure we need to overplay this too much. I think of it as the value of network effects - the more people involved, the better the quality of standards development, the better the output, the more adoption of the output. And so the more accessible the IETF is, the better. 

And we have tons of no cost ways to interact but we do have some costs to cover. Other SSOs may have entirely different revenue models.

**Comment by mirjak** [comment]
I think this can be closed with no action? @richsalz ?

**Comment by richsalz** [comment]
I am fine with just closing this.
