### ISSUE TITLE
Provide more guidance when the free option can/should be used or not

### ISSUE THREAD

**Issue by mirjak** [mirjak/draft-kuehlewind-shmoo-remote-fee#8]
Text proposed by Brian Carpenter via email:
"Free registration is not intended for use by businesses to avoid paying
their fair share of the IETF's running costs. Whatever conditions are
used to qualify participants for free participation, the IETF retains
the right to deny free registration to participants whose business sponsor
is clearly able to pay its fair share."

**Comment by dhruvdhody** [comment]
Just a caveat. Even in these "businesses", there are engineers/testers/implementors who are in departments/geographical locations and do not have access to the kind of budget required. A free option should be available to them. 

It is a hard conversation for a young engineer to justify the cost to the mid-level managers within the limited team budgets to attend IETF. Yes, we could shame the business into providing support, but I would rather provide free options to whoever asks for it.

**Comment by mirjak** [comment]
Yes. I said this in mail but let me add this here as well: my intention would really be to ensure that anybody who would have called in remotely previously (just because it's free and they have time and actually don't need to ask for approval) will still join now. However, there was also a concern that, maybe even by some regulatory constraints, employees could be always required to take the cheapest option available. After all, I guess this a challenge for the LLC. What we need to do as a community is to clearly state the principles and maybe on top of that make sure we do our best in stating these principles such that nobody sees a barrier to use this option but instead rather chooses not to participate

**Comment by dhruvdhody** [comment]
Yes, perhaps LLC can find a way to handle the regulatory constraint and make sure this is not considered as the "cheapest option" but something else entirely! Thanks!

**Comment by martinduke** [comment]
It might be that this draft, as written, is the maximum viable consensus. If not, it might be helpful to the LLC to provide a little guidance on what are "legitimate" reasons to not pay.

The status quo is, of course, simply declaring that you have a hardship. That's sufficient in practice for most expense account types to keep paying. It appears we have consensus that that is a worthwhile outcome.

But there were some calls before 108 for particular groups to be free/discounted without a specific hardship. These included:
- Retirees
- Students
- Residents of developing countries
- Attended X of the last Y in-person meetings remotely
- First-timers
- People who attend fewer than Z sessions
- Unemployed/Self-employed

If there is actually community consensus for any of these, that would be helpful.

**Comment by mirjak** [comment]
Addressed by PR #10 based on the understanding of the discussion on the mailing list. There have been many more discussion about misuse but it seems this is the level we can talk about this in this document and leave the rest to the LLC and community in case this becomes a problem.
