### ISSUE TITLE
T-shirts for free registrations? (was: Various suggestions)

### ISSUE THREAD

**Issue by toerless** [mirjak/draft-kuehlewind-shmoo-remote-fee#9]
Some textual nitpicking:

I don't think it is correct to say "because most participants paid in-person fees, ", i think the reason was "because a) the in-person attendants paid and b) their numbers where sufficient to support the meeting". This may be important because there is ultimately the question of the total number of paying attendants.

After reciting rfc3935 it might be useful to state that the IETF has interpreted "open" to mean "open and free (of charge)". That might have been implicit in rfc3935 but it is not anymore, hence more modern terms like FOSS (Free and Open...).

Maybe add something to the extend of: If paid remote attendance is counted towards NomCom eligibility then so must free online attendance. 

Not quite sure how how to define differences in paid vs. free attendance, but for example t-shirts could of course NOT be given to free attendants. Aka: may make sense to figure out text for this.

**Comment by mirjak** [comment]
I addressed your first two points.

I don't think the document should say anything about NomCom eligibility. I think that's a separate topic and we already have a separate effort working on this.

Regarding t-shirts... not sure this document should say anything on that level of detail but maybe that also needs more discussion about what are acceptable differences for free vs. paid and what not...? 
Currently the document says

`any free registration option must offer the same degree of interactivity and functionality available to paid remote attendees.`

I guess that simply leaves the decision about t-shirt to the LLC which is okay for me.

**Comment by mirjak** [comment]
Marking this as resolved. Please re-open or open a new issue if not everything was addressed.
